version: "3"
services:
    task_tracker:
        build: ./d3_project/
        environment:
            API_PORT: 8000
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: db_user
            DB_PASS: db_password
            DB_NAME: tasks_tracker
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=tasks_tracker
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=db_password
